// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"com.example/example/bootstrap"
	"com.example/example/pkg/config"
	"com.example/example/pkg/orm"
	"com.example/example/pkg/xcasbin"
	"com.example/example/pkg/xjwt"
	"com.example/example/repository"
	"com.example/example/service"
	"com.example/example/web/controller"
	"com.example/example/web/middleware"
	"com.example/example/web/router"
)

// Injectors from wire.go:

func BuildServer(conf *config.Config) *bootstrap.Server {
	db := orm.NewDB(conf)
	engine := bootstrap.NewGin()
	helloController := controller.NewHelloController()
	jwtHelper := xjwt.NewJwtHelper(conf)
	enforcer := xcasbin.NewCasbin(db)
	auth := middleware.NewAuth(jwtHelper, enforcer)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository, jwtHelper, enforcer)
	userController := controller.NewUserController(userService)
	permissionRepository := repository.NewPermissionRepository(db)
	permissionService := service.NewPermissionService(permissionRepository, enforcer)
	permissionController := controller.NewPermissionController(permissionService)
	roleRepository := repository.NewRoleRepository(db)
	rolePermissionDao := repository.NewRolePermissionRepository(db)
	roleService := service.NewRoleService(roleRepository, rolePermissionDao, permissionRepository, enforcer, userRepository)
	roleController := controller.NewRoleController(roleService, userService)
	routerRouter := &router.Router{
		Engine:        engine,
		HelloApi:      helloController,
		Auth:          auth,
		UserApi:       userController,
		PermissionApi: permissionController,
		RoleApi:       roleController,
	}
	server := &bootstrap.Server{
		Config: conf,
		DB:     db,
		Router: routerRouter,
		Engine: engine,
	}
	return server
}
